### ISSUE TITLE
the plot function gives an AttributeError with inline plot

### ISSUE THREAD

**Issue by mattijn** [droyed/benchit#1]
First of all, thanks for making this package. 

When using a Jupyter Notebook the following code gives an `AttributeError` in the `plot` function using `%matplotlib inline`:

```python
import numpy as np
funcs = [np.sum,np.prod,np.max]
inputs = [np.random.rand(i) for i in 10**np.arange(5)]

import benchit
t = benchit.timings(funcs, inputs)
```
```python
%matplotlib inline
t.plot()
```

> ```bash
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-114-d150a948a29e> in <module>
> ----> 1 t.plot()
> 
> D:\Software\Miniconda3\lib\site-packages\benchit\main.py in plot(self, set_xticks_from_index, xlabel, ylabel, colormap, marker, logx, logy, grid, linewidth, add_specs_as, modules, save)
>     577 
>     578         if add_specs_as == 'title':
> --> 579             _add_specs_as_title(dfp, modules=modules)
>     580         elif add_specs_as == 'textbox':
>     581             _add_specs_as_textbox(dfp, modules=modules)
> 
> D:\Software\Miniconda3\lib\site-packages\benchit\plot_utils.py in _add_specs_as_title(ax, modules)
>     206 
>     207     figManager = plt.get_current_fig_manager()
> --> 208     figManager.window.showMaximized()
>     209 
>     210     plt.pause(0.1)
> 
> AttributeError: 'FigureManagerBase' object has no attribute 'window'
> ```

**Comment by droyed** [comment]
@mattijn Appreciate the feedback! That should be fixed in the latest release `0.0.3`. Also, I would recommend, using `%matplotlib notebook` for interactive plots with specs in the title.
